version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-networks

  sls:
    build:
      context: ./docker/sls
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    volumes:
      - ./src/sls:/app # <= いずれ作成するサーバレスアーキテクチャをボリュームに追加
    working_dir: /app
    ports:
      - 3333:3000 # <= 3000を3333にマッピング
    env_file:
      - .env
    networks:
      - localstack-networks

networks:
  localstack-networks:
    driver: bridge
